"""Shell completion 脚本生成模块"""
import os
import sys
from pathlib import Path
from typing import Optional


POWERSHELL_COMPLETION = '''
# PowerShell completion for mem command
# Auto-generated by feishu-long-memory-agent

$scriptBlock = {
    param($wordToComplete, $commandAst, $cursorPosition)

    # 获取当前命令行内容
    $commandLine = $commandAst.ToString()

    # 解析已输入的命令和子命令
    $words = $commandLine -split '\\s+'
    $command = if ($words.Length -ge 2) { $words[1] } else { '' }

    # 根据子命令提供建议
    $completions = @()

    switch ($command) {
        'search' {
            # 搜索命令的补全：调用 mem suggest
            if ($wordToComplete) {
                try {
                    $suggestions = & mem suggest $wordToComplete 2>$null
                    $completions = $suggestions -split '\\n' | Where-Object { $_ -ne '' }
                } catch {
                    $completions = @()
                }
            }
        }
        'memorize' {
            # memorize 命令的类型补全
            $completions = @('cli_command', 'user_preference', 'docker启动命令', '周报发送命令')
        }
        'workflow' {
            # workflow 子命令补全
            $completions = @('save', 'run')
        }
        default {
            # 主命令补全
            $completions = @('memorize', 'search', 'list', 'watch', 'suggest', 'workflow', 'clear', 'configure', 'completion')
        }
    }

    # 过滤匹配的建议
    $completions | Where-Object { $_ -like "$wordToComplete*" } |
        ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
}

Register-ArgumentCompleter -CommandName mem -ScriptBlock $scriptBlock
'''

BASH_COMPLETION = '''
# Bash completion for mem command
# Auto-generated by feishu-long-memory-agent

_mem_completions() {
    local cur prev commands
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    # 主命令列表
    commands="memorize search list watch suggest workflow clear configure completion"

    # 根据前一个命令提供建议
    case "${prev}" in
        search)
            # 搜索命令的补全：调用 mem suggest
            if [ -n "$cur" ]; then
                local suggestions
                suggestions=$(mem suggest "$cur" 2>/dev/null)
                COMPREPLY=( $(compgen -W "$suggestions" -- "$cur") )
            fi
            return 0
            ;;
        memorize)
            # memorize 命令的类型补全
            local types="cli_command user_preference docker启动命令 周报发送命令"
            COMPREPLY=( $(compgen -W "$types" -- "$cur") )
            return 0
            ;;
        workflow)
            # workflow 子命令补全
            COMPREPLY=( $(compgen -W "save run" -- "$cur") )
            return 0
            ;;
        completion)
            # completion 子命令补全
            COMPREPLY=( $(compgen -W "install uninstall" -- "$cur") )
            return 0
            ;;
        *)
            ;;
    esac

    # 主命令补全
    COMPREPLY=( $(compgen -W "$commands" -- "$cur") )
    return 0
}

complete -F _mem_completions mem
'''

ZSH_COMPLETION = '''
#compdef mem
# Zsh completion for mem command
# Auto-generated by feishu-long-memory-agent

_mem() {
    local -a commands
    commands=(
        'memorize:主动注入记忆'
        'search:搜索相关记忆'
        'list:查看历史记忆列表'
        'watch:扫描命令行历史，自动记录高频命令'
        'suggest:输出命令建议'
        'workflow:工作流模板管理'
        'clear:清空所有记忆'
        'configure:配置CLI工具'
        'completion:管理shell补全'
    )

    _arguments -C \
        '1: :->command' \
        '*: :->args'

    case $state in
        command)
            _describe -t commands 'mem command' commands
            ;;
        args)
            case $words[1] in
                search)
                    # 搜索命令的补全：调用 mem suggest
                    if [ -n "$words[-1]" ]; then
                        local -a suggestions
                        suggestions=(${(f)"$(mem suggest $words[-1] 2>/dev/null)"})
                        _describe -t suggestions 'suggestions' suggestions
                    fi
                    ;;
                memorize)
                    # memorize 命令的类型补全
                    local -a types
                    types=(
                        'cli_command:CLI命令'
                        'user_preference:用户偏好'
                        'docker启动命令:Docker命令'
                        '周报发送命令:周报命令'
                    )
                    _describe -t types 'memory type' types
                    ;;
                workflow)
                    # workflow 子命令补全
                    local -a workflow_cmds
                    workflow_cmds=(
                        'save:保存工作流模板'
                        'run:执行已保存的工作流'
                    )
                    _describe -t workflow_cmds 'workflow command' workflow_cmds
                    ;;
                completion)
                    # completion 子命令补全
                    local -a completion_cmds
                    completion_cmds=(
                        'install:安装补全脚本'
                        'uninstall:卸载补全脚本'
                    )
                    _describe -t completion_cmds 'completion command' completion_cmds
                    ;;
            esac
            ;;
    esac
}

_mem "$@"
'''


def get_shell_type() -> str:
    """检测当前shell类型"""
    if sys.platform == "win32":
        return "powershell"
    shell = os.environ.get("SHELL", "")
    if "zsh" in shell:
        return "zsh"
    return "bash"


def get_completion_script(shell_type: Optional[str] = None) -> str:
    """获取指定shell类型的补全脚本"""
    shell = shell_type or get_shell_type()

    if shell == "powershell":
        return POWERSHELL_COMPLETION
    elif shell == "zsh":
        return ZSH_COMPLETION
    else:
        return BASH_COMPLETION


def get_install_path(shell_type: Optional[str] = None) -> Path:
    """获取补全脚本安装路径"""
    shell = shell_type or get_shell_type()
    home = Path.home()

    if shell == "powershell":
        # PowerShell profile 路径
        return home / "Documents" / "PowerShell" / "mem-completion.ps1"
    elif shell == "zsh":
        # Zsh 补全目录
        completion_dir = home / ".zsh" / "completions"
        return completion_dir / "_mem"
    else:
        # Bash 补全目录
        return home / ".bash_completion.d" / "mem"


def install_completion(shell_type: Optional[str] = None, force: bool = False) -> dict:
    """
    安装shell补全脚本

    Args:
        shell_type: shell类型（powershell/bash/zsh）
        force: 是否强制覆盖

    Returns:
        安装结果
    """
    shell = shell_type or get_shell_type()
    script = get_completion_script(shell)
    install_path = get_install_path(shell)

    # 检查是否已安装
    if install_path.exists() and not force:
        return {
            "status": "skipped",
            "message": f"补全脚本已存在: {install_path}",
            "path": str(install_path),
            "hint": "使用 --force 参数强制覆盖"
        }

    # 创建目录
    install_path.parent.mkdir(parents=True, exist_ok=True)

    # 写入脚本
    install_path.write_text(script, encoding="utf-8")

    # 生成激活命令
    activate_cmd = _get_activate_command(shell, install_path)

    return {
        "status": "ok",
        "message": f"补全脚本已安装到: {install_path}",
        "path": str(install_path),
        "shell": shell,
        "activate_command": activate_cmd
    }


def uninstall_completion(shell_type: Optional[str] = None) -> dict:
    """
    卸载shell补全脚本

    Args:
        shell_type: shell类型（powershell/bash/zsh）

    Returns:
        卸载结果
    """
    shell = shell_type or get_shell_type()
    install_path = get_install_path(shell)

    if not install_path.exists():
        return {
            "status": "skipped",
            "message": f"补全脚本不存在: {install_path}"
        }

    install_path.unlink()

    return {
        "status": "ok",
        "message": f"补全脚本已卸载: {install_path}"
    }


def _get_activate_command(shell: str, script_path: Path) -> str:
    """获取激活补全脚本的命令"""
    if shell == "powershell":
        return f'. "{script_path}"'
    elif shell == "zsh":
        return f'source "{script_path}"'
    else:
        return f'source "{script_path}"'


def get_profile_path(shell: Optional[str] = None) -> Optional[Path]:
    """获取shell配置文件路径"""
    shell = shell or get_shell_type()
    home = Path.home()

    if shell == "powershell":
        # PowerShell profile 路径
        profile_path = home / "Documents" / "PowerShell" / "Microsoft.PowerShell_profile.ps1"
        if not profile_path.exists():
            profile_path = home / "Documents" / "WindowsPowerShell" / "Microsoft.PowerShell_profile.ps1"
        return profile_path if profile_path.exists() else None
    elif shell == "zsh":
        profile_path = home / ".zshrc"
        return profile_path if profile_path.exists() else None
    else:
        profile_path = home / ".bashrc"
        if not profile_path.exists():
            profile_path = home / ".bash_profile"
        return profile_path if profile_path.exists() else None


def get_setup_instructions(shell: Optional[str] = None) -> str:
    """获取设置说明"""
    shell = shell or get_shell_type()
    script_path = get_install_path(shell)
    activate_cmd = _get_activate_command(shell, script_path)

    instructions = f"""
Shell补全设置说明 ({shell}):

1. 安装补全脚本:
   mem completion install

2. 激活补全（当前会话）:
   {activate_cmd}

3. 永久激活（添加到配置文件）:
   echo '{activate_cmd}' >> {_get_profile_path_hint(shell)}

4. 重新加载配置:
   {_get_reload_command(shell)}

5. 测试补全:
   输入 'mem se' 然后按 Tab 键
"""
    return instructions


def _get_profile_path_hint(shell: str) -> str:
    """获取配置文件路径提示"""
    if shell == "powershell":
        return "$PROFILE"
    elif shell == "zsh":
        return "~/.zshrc"
    else:
        return "~/.bashrc"


def _get_reload_command(shell: str) -> str:
    """获取重新加载配置的命令"""
    if shell == "powershell":
        return ". $PROFILE"
    elif shell == "zsh":
        return "source ~/.zshrc"
    else:
        return "source ~/.bashrc"
